//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipboardMonitorLite.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_nl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_nl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipboardMonitorLite.Languages.lang_nl", typeof(lang_nl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informatie Over.
        /// </summary>
        internal static string Btn_About {
            get {
                return ResourceManager.GetString("Btn_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan.
        /// </summary>
        internal static string Btn_Apply {
            get {
                return ResourceManager.GetString("Btn_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoeken.
        /// </summary>
        internal static string Btn_Browse {
            get {
                return ResourceManager.GetString("Btn_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoeken naar Updates.
        /// </summary>
        internal static string Btn_CheckForUpdates {
            get {
                return ResourceManager.GetString("Btn_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sluiten.
        /// </summary>
        internal static string Btn_Close {
            get {
                return ResourceManager.GetString("Btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeg Klembord.
        /// </summary>
        internal static string Btn_EmptyClipboard {
            get {
                return ResourceManager.GetString("Btn_EmptyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeg Geschiedenis.
        /// </summary>
        internal static string Btn_EmptyHistory {
            get {
                return ResourceManager.GetString("Btn_EmptyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opties.
        /// </summary>
        internal static string Btn_MoreOptions {
            get {
                return ResourceManager.GetString("Btn_MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeg Klembord Automatisch.
        /// </summary>
        internal static string Check_AutoClearClipboard {
            get {
                return ResourceManager.GetString("Check_AutoClearClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laat een notificatie zien als ik iets kopieer.
        /// </summary>
        internal static string Check_NotifyOfCopy {
            get {
                return ResourceManager.GetString("Check_NotifyOfCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open met Windows.
        /// </summary>
        internal static string Check_OpenWithWin {
            get {
                return ResourceManager.GetString("Check_OpenWithWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan naar Bestand.
        /// </summary>
        internal static string Check_SaveToFile {
            get {
                return ResourceManager.GetString("Check_SaveToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laat een Donatie knop zien op het hoofdvenster.
        /// </summary>
        internal static string Check_ShowDonation {
            get {
                return ResourceManager.GetString("Check_ShowDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start het programma geminimaliseerd.
        /// </summary>
        internal static string Check_StartMinimized {
            get {
                return ResourceManager.GetString("Check_StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update als het programma opgestart word.
        /// </summary>
        internal static string Check_UpdateOnStartup {
            get {
                return ResourceManager.GetString("Check_UpdateOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruik een wit icoon op de taakbalk.
        /// </summary>
        internal static string Check_UseWhiteIcon {
            get {
                return ResourceManager.GetString("Check_UseWhiteIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toevoegen in echte tijd.
        /// </summary>
        internal static string Check_WriteInRealTime {
            get {
                return ResourceManager.GetString("Check_WriteInRealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uur.
        /// </summary>
        internal static string ComboBox_Time_Hour {
            get {
                return ResourceManager.GetString("ComboBox_Time_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconde.
        /// </summary>
        internal static string ComboBox_Time_Sec {
            get {
                return ResourceManager.GetString("ComboBox_Time_Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekst Bestand|*.txt.
        /// </summary>
        internal static string File_TextFile {
            get {
                return ResourceManager.GetString("File_TextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acties.
        /// </summary>
        internal static string GroupBox_Actions {
            get {
                return ResourceManager.GetString("GroupBox_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gedrag en visuelen.
        /// </summary>
        internal static string GroupBox_BehaviourAndVisuals {
            get {
                return ResourceManager.GetString("GroupBox_BehaviourAndVisuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gekopieerde bestanden.
        /// </summary>
        internal static string GroupBox_CopiedItems {
            get {
                return ResourceManager.GetString("GroupBox_CopiedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algemeen.
        /// </summary>
        internal static string GroupBox_General {
            get {
                return ResourceManager.GetString("GroupBox_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan naar bestand opties.
        /// </summary>
        internal static string GroupBox_SaveToFileSettings {
            get {
                return ResourceManager.GetString("GroupBox_SaveToFileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update en huidige versie.
        /// </summary>
        internal static string GroupBox_UpdateAndCurrentVersion {
            get {
                return ResourceManager.GetString("GroupBox_UpdateAndCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iedere.
        /// </summary>
        internal static string Label_Every {
            get {
                return ResourceManager.GetString("Label_Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestandslocatie.
        /// </summary>
        internal static string Label_FileLocation {
            get {
                return ResourceManager.GetString("Label_FileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taal.
        /// </summary>
        internal static string Label_Lang {
            get {
                return ResourceManager.GetString("Label_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuut.
        /// </summary>
        internal static string Label_Minutes {
            get {
                return ResourceManager.GetString("Label_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! Het lijkt erop dat je dit
        ///programma hebt opgestard zonder
        ///administratieve rechten. Probeer
        ///het programma nog maals op te
        ///starten als administrator..
        /// </summary>
        internal static string Label_NoAdminRights {
            get {
                return ResourceManager.GetString("Label_NoAdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laat notificatie zien voor (Seconde).
        /// </summary>
        internal static string Label_ShowNotificationFor {
            get {
                return ResourceManager.GetString("Label_ShowNotificationFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versie .
        /// </summary>
        internal static string Label_Version {
            get {
                return ResourceManager.GetString("Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als ik het hoofdvenster sluit.
        /// </summary>
        internal static string Label_WhenMainWindowClosed {
            get {
                return ResourceManager.GetString("Label_WhenMainWindowClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als Real Time uitgezet is, zal
        ///de applicatie alleen toegang
        ///krijgen en schrijven als het
        ///bestand gesloten is..
        /// </summary>
        internal static string Label_WriteRealTimeInfo {
            get {
                return ResourceManager.GetString("Label_WriteRealTimeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard Monitor Lite.
        /// </summary>
        internal static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeg Klembord.
        /// </summary>
        internal static string Menu_EmptyClipboard {
            get {
                return ResourceManager.GetString("Menu_EmptyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeg Geschiedenis.
        /// </summary>
        internal static string Menu_EmptyHistory {
            get {
                return ResourceManager.GetString("Menu_EmptyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verlaten.
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openen.
        /// </summary>
        internal static string Menu_Restore {
            get {
                return ResourceManager.GetString("Menu_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ik zal meteen de knop verschuilen, maar voordat ik dit doe, wil ik even zeggen dat ik alleen werk aan deze applicatie, met wat hulp van een paar vrienden, maar ik krijg geen financiële steun. Ik heb geen behoeften om mensen te vragen voor geld om deze applicatie te gebruiken, en ik wil geen advertenties in de applicatie plaatsen, om welke vorm dan ook. Als je mij wilt steunen en mijn werk verbeteren in de toekomst, denk dan misschien aan doneren als optie van steun.. Bedankt! : ).
        /// </summary>
        internal static string MsgBox_DonateHide {
            get {
                return ResourceManager.GetString("MsgBox_DonateHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om de veranderingen te laten werken, herstart de applicatie..
        /// </summary>
        internal static string MsgBox_RestartApp {
            get {
                return ResourceManager.GetString("MsgBox_RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschuil de Donatie knop.
        /// </summary>
        internal static string MsgBox_Title_DonateHide {
            get {
                return ResourceManager.GetString("MsgBox_Title_DonateHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herstart de app.
        /// </summary>
        internal static string MsgBox_TitleRestartApp {
            get {
                return ResourceManager.GetString("MsgBox_TitleRestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De applicatie is nog actief! Als je de applicatie wilt beëindigen, druk dan met de rechtermuisknop op het taakbalk icoontje, en druk op &quot;Afsluiten&quot;..
        /// </summary>
        internal static string Notif_AppStillRunning {
            get {
                return ResourceManager.GetString("Notif_AppStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item gekopieerd naar klembord!.
        /// </summary>
        internal static string Notif_ItemCopied {
            get {
                return ResourceManager.GetString("Notif_ItemCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicatie is nog actief!.
        /// </summary>
        internal static string Notif_Title_AppStillRunning {
            get {
                return ResourceManager.GetString("Notif_Title_AppStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item gekopieerd!.
        /// </summary>
        internal static string Notif_Title_ItemCopied {
            get {
                return ResourceManager.GetString("Notif_Title_ItemCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opties.
        /// </summary>
        internal static string Options_Title {
            get {
                return ResourceManager.GetString("Options_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toevoegen tot bestand.
        /// </summary>
        internal static string Radio_Append {
            get {
                return ResourceManager.GetString("Radio_Append", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeg bestand en vervang het bestand.
        /// </summary>
        internal static string Radio_EmptyAndReplace {
            get {
                return ResourceManager.GetString("Radio_EmptyAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beëindig de applicatie.
        /// </summary>
        internal static string Radio_ExitApp {
            get {
                return ResourceManager.GetString("Radio_ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalizeer in de systeembalk.
        /// </summary>
        internal static string Radio_Minimize {
            get {
                return ResourceManager.GetString("Radio_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sla geschiedenis op als tekst bestand.
        /// </summary>
        internal static string SaveAsTextFile {
            get {
                return ResourceManager.GetString("SaveAsTextFile", resourceCulture);
            }
        }
    }
}
