//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipboardMonitorLite.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_sr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_sr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipboardMonitorLite.Languages.lang_sr", typeof(lang_sr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О програму.
        /// </summary>
        internal static string Btn_About {
            get {
                return ResourceManager.GetString("Btn_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примени.
        /// </summary>
        internal static string Btn_Apply {
            get {
                return ResourceManager.GetString("Btn_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прелистај.
        /// </summary>
        internal static string Btn_Browse {
            get {
                return ResourceManager.GetString("Btn_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Провери за нову верзију.
        /// </summary>
        internal static string Btn_CheckForUpdates {
            get {
                return ResourceManager.GetString("Btn_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Затвори.
        /// </summary>
        internal static string Btn_Close {
            get {
                return ResourceManager.GetString("Btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпразни копирани текст.
        /// </summary>
        internal static string Btn_EmptyClipboard {
            get {
                return ResourceManager.GetString("Btn_EmptyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избриши Историју.
        /// </summary>
        internal static string Btn_EmptyHistory {
            get {
                return ResourceManager.GetString("Btn_EmptyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEEDS TRANSLATION.
        /// </summary>
        internal static string Btn_Generate {
            get {
                return ResourceManager.GetString("Btn_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опције.
        /// </summary>
        internal static string Btn_MoreOptions {
            get {
                return ResourceManager.GetString("Btn_MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEEDS TRANSLATION.
        /// </summary>
        internal static string Btn_ShowPassword {
            get {
                return ResourceManager.GetString("Btn_ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аутоматски Избриши копирани текст.
        /// </summary>
        internal static string Check_AutoClearClipboard {
            get {
                return ResourceManager.GetString("Check_AutoClearClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укључи име уређаја у копи историју.
        /// </summary>
        internal static string Check_IncludeDeviceName {
            get {
                return ResourceManager.GetString("Check_IncludeDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ограничи саобраћај података.
        /// </summary>
        internal static string Check_LimitTraffic {
            get {
                return ResourceManager.GetString("Check_LimitTraffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обавести ме ако ископирам нешто.
        /// </summary>
        internal static string Check_NotifyOfCopy {
            get {
                return ResourceManager.GetString("Check_NotifyOfCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Онлине режим.
        /// </summary>
        internal static string Check_OnlineMode {
            get {
                return ResourceManager.GetString("Check_OnlineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отвори са Windows.
        /// </summary>
        internal static string Check_OpenWithWin {
            get {
                return ResourceManager.GetString("Check_OpenWithWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запамти датотеку.
        /// </summary>
        internal static string Check_SaveToFile {
            get {
                return ResourceManager.GetString("Check_SaveToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEEDS TRANSLATION.
        /// </summary>
        internal static string Check_Show {
            get {
                return ResourceManager.GetString("Check_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прикажи дугме за донацију на главну форму.
        /// </summary>
        internal static string Check_ShowDonation {
            get {
                return ResourceManager.GetString("Check_ShowDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почни минимазиран.
        /// </summary>
        internal static string Check_StartMinimized {
            get {
                return ResourceManager.GetString("Check_StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ажурирај на покретанје.
        /// </summary>
        internal static string Check_UpdateOnStartup {
            get {
                return ResourceManager.GetString("Check_UpdateOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укључи Временску Ознаку.
        /// </summary>
        internal static string Check_UseTimestamp {
            get {
                return ResourceManager.GetString("Check_UseTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користи белу иконицу у систем таскбар.
        /// </summary>
        internal static string Check_UseWhiteIcon {
            get {
                return ResourceManager.GetString("Check_UseWhiteIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пиши у реално време.
        /// </summary>
        internal static string Check_WriteInRealTime {
            get {
                return ResourceManager.GetString("Check_WriteInRealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сат.
        /// </summary>
        internal static string ComboBox_Time_Hour {
            get {
                return ResourceManager.GetString("ComboBox_Time_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Секунда.
        /// </summary>
        internal static string ComboBox_Time_Sec {
            get {
                return ResourceManager.GetString("ComboBox_Time_Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст податак|*.txt.
        /// </summary>
        internal static string File_TextFile {
            get {
                return ResourceManager.GetString("File_TextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEEDS TRANSLATION.
        /// </summary>
        internal static string Group_GroupSettings {
            get {
                return ResourceManager.GetString("Group_GroupSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акције.
        /// </summary>
        internal static string GroupBox_Actions {
            get {
                return ResourceManager.GetString("GroupBox_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Понашање и  Визуали.
        /// </summary>
        internal static string GroupBox_BehaviourAndVisuals {
            get {
                return ResourceManager.GetString("GroupBox_BehaviourAndVisuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копирани предмети.
        /// </summary>
        internal static string GroupBox_CopiedItems {
            get {
                return ResourceManager.GetString("GroupBox_CopiedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Генерално.
        /// </summary>
        internal static string GroupBox_General {
            get {
                return ResourceManager.GetString("GroupBox_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Онлајн понашање апликације.
        /// </summary>
        internal static string GroupBox_OnlineBehaviour {
            get {
                return ResourceManager.GetString("GroupBox_OnlineBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интернет подешавања.
        /// </summary>
        internal static string GroupBox_OnlineSettings {
            get {
                return ResourceManager.GetString("GroupBox_OnlineSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запамти у подешавања за датотеку.
        /// </summary>
        internal static string GroupBox_SaveToFileSettings {
            get {
                return ResourceManager.GetString("GroupBox_SaveToFileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kашњење пре реконекције.
        /// </summary>
        internal static string GroupBox_TimeBeforeReconnect {
            get {
                return ResourceManager.GetString("GroupBox_TimeBeforeReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ажурирана верзија и информација о тренутној верзији.
        /// </summary>
        internal static string GroupBox_UpdateAndCurrentVersion {
            get {
                return ResourceManager.GetString("GroupBox_UpdateAndCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сви.
        /// </summary>
        internal static string Label_Every {
            get {
                return ResourceManager.GetString("Label_Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локација Датотеке.
        /// </summary>
        internal static string Label_FileLocation {
            get {
                return ResourceManager.GetString("Label_FileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEEDS TRANSLATION.
        /// </summary>
        internal static string Label_GroupId {
            get {
                return ResourceManager.GetString("Label_GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Језик.
        /// </summary>
        internal static string Label_Lang {
            get {
                return ResourceManager.GetString("Label_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минут.
        /// </summary>
        internal static string Label_Minutes {
            get {
                return ResourceManager.GetString("Label_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извини! Изгледа да немаш административни
        ///приступ, или апликација није успела да
        ///се покрене, покушај да рестартујеш
        ///апликацију као администратор..
        /// </summary>
        internal static string Label_NoAdminRights {
            get {
                return ResourceManager.GetString("Label_NoAdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подеси како ће апликацијa руковати
        ///онлајн интеракције са осталим уређајима..
        /// </summary>
        internal static string Label_OnlineBehaviourExplanation {
            get {
                return ResourceManager.GetString("Label_OnlineBehaviourExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEEDS TRANSLATION.
        /// </summary>
        internal static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Секунде.
        /// </summary>
        internal static string Label_Seconds {
            get {
                return ResourceManager.GetString("Label_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прикажи нотификацију за (Секунде).
        /// </summary>
        internal static string Label_ShowNotificationFor {
            get {
                return ResourceManager.GetString("Label_ShowNotificationFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верзија .
        /// </summary>
        internal static string Label_Version {
            get {
                return ResourceManager.GetString("Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Када затворим главни прозор.
        /// </summary>
        internal static string Label_WhenMainWindowClosed {
            get {
                return ResourceManager.GetString("Label_WhenMainWindowClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ако је реално време икључено, апликација
        ///ће само приступити и писати у датотеку
        ///када је затворена..
        /// </summary>
        internal static string Label_WriteRealTimeInfo {
            get {
                return ResourceManager.GetString("Label_WriteRealTimeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard Monitor Lite.
        /// </summary>
        internal static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпразни Копирани текст.
        /// </summary>
        internal static string Menu_EmptyClipboard {
            get {
                return ResourceManager.GetString("Menu_EmptyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпразни Историју.
        /// </summary>
        internal static string Menu_EmptyHistory {
            get {
                return ResourceManager.GetString("Menu_EmptyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Затвори.
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отвори.
        /// </summary>
        internal static string Menu_Restore {
            get {
                return ResourceManager.GetString("Menu_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сакрићу дугме одмах, али пре него што то урадим, само сам хтео да кажем, ја радим на овој апликацији углавном сам, са помоћ од неких пријатеља, али не добијам никакву финанцијску помоћ, и немам намеру да тражим новац од народа само да би користили ову апликацију, и ја одбијам да убацим реклама у будућности, у било којој форми. Ако би сте желели да подржите моји посао и да ми помогнете да их унапредим у будућност, молим вас да размислите о донацији, хвала вам! :).
        /// </summary>
        internal static string MsgBox_DonateHide {
            get {
                return ResourceManager.GetString("MsgBox_DonateHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да примениш промене, молимо вас да рестартујете апликацију..
        /// </summary>
        internal static string MsgBox_RestartApp {
            get {
                return ResourceManager.GetString("MsgBox_RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сакриј дугме за донацију.
        /// </summary>
        internal static string MsgBox_Title_DonateHide {
            get {
                return ResourceManager.GetString("MsgBox_Title_DonateHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рестартуј апликацију.
        /// </summary>
        internal static string MsgBox_TitleRestartApp {
            get {
                return ResourceManager.GetString("MsgBox_TitleRestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Апликација још увер ради! Ако желите да изађете, молимо вас да десним кликом кликнете на таскбар иконицу и изаберете Затвори!.
        /// </summary>
        internal static string Notif_AppStillRunning {
            get {
                return ResourceManager.GetString("Notif_AppStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предмет копиран у clipboard!.
        /// </summary>
        internal static string Notif_ItemCopied {
            get {
                return ResourceManager.GetString("Notif_ItemCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Апликација још увер ради!.
        /// </summary>
        internal static string Notif_Title_AppStillRunning {
            get {
                return ResourceManager.GetString("Notif_Title_AppStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предмет копиран!.
        /// </summary>
        internal static string Notif_Title_ItemCopied {
            get {
                return ResourceManager.GetString("Notif_Title_ItemCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опције.
        /// </summary>
        internal static string Options_Title {
            get {
                return ResourceManager.GetString("Options_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати датотеку.
        /// </summary>
        internal static string Radio_Append {
            get {
                return ResourceManager.GetString("Radio_Append", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпразни датотеку и замени.
        /// </summary>
        internal static string Radio_EmptyAndReplace {
            get {
                return ResourceManager.GetString("Radio_EmptyAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изађи из апликације.
        /// </summary>
        internal static string Radio_ExitApp {
            get {
                return ResourceManager.GetString("Radio_ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимазирај на системску подлогу.
        /// </summary>
        internal static string Radio_Minimize {
            get {
                return ResourceManager.GetString("Radio_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прими само.
        /// </summary>
        internal static string Radio_ReceiveOnly {
            get {
                return ResourceManager.GetString("Radio_ReceiveOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошаљи и Прими.
        /// </summary>
        internal static string Radio_SendAndReceive {
            get {
                return ResourceManager.GetString("Radio_SendAndReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошаљи само.
        /// </summary>
        internal static string Radio_SendOnly {
            get {
                return ResourceManager.GetString("Radio_SendOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запамти историју као текст податак.
        /// </summary>
        internal static string SaveAsTextFile {
            get {
                return ResourceManager.GetString("SaveAsTextFile", resourceCulture);
            }
        }
    }
}
