//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipboardMonitorLite.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_por {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_por() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipboardMonitorLite.Languages.lang_por", typeof(lang_por).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre.
        /// </summary>
        internal static string Btn_About {
            get {
                return ResourceManager.GetString("Btn_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar.
        /// </summary>
        internal static string Btn_Apply {
            get {
                return ResourceManager.GetString("Btn_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurar.
        /// </summary>
        internal static string Btn_Browse {
            get {
                return ResourceManager.GetString("Btn_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificar atualizações.
        /// </summary>
        internal static string Btn_CheckForUpdates {
            get {
                return ResourceManager.GetString("Btn_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        internal static string Btn_Close {
            get {
                return ResourceManager.GetString("Btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área de transferência vazia.
        /// </summary>
        internal static string Btn_EmptyClipboard {
            get {
                return ResourceManager.GetString("Btn_EmptyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to História vazia.
        /// </summary>
        internal static string Btn_EmptyHistory {
            get {
                return ResourceManager.GetString("Btn_EmptyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEEDS TRANSLATION.
        /// </summary>
        internal static string Btn_Generate {
            get {
                return ResourceManager.GetString("Btn_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opções.
        /// </summary>
        internal static string Btn_MoreOptions {
            get {
                return ResourceManager.GetString("Btn_MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEEDS TRANSLATION.
        /// </summary>
        internal static string Btn_ShowPassword {
            get {
                return ResourceManager.GetString("Btn_ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar a área de transferência automaticamente.
        /// </summary>
        internal static string Check_AutoClearClipboard {
            get {
                return ResourceManager.GetString("Check_AutoClearClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir nome do dispositivo no histórico de cópias.
        /// </summary>
        internal static string Check_IncludeDeviceName {
            get {
                return ResourceManager.GetString("Check_IncludeDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limitar o tráfego de dados.
        /// </summary>
        internal static string Check_LimitTraffic {
            get {
                return ResourceManager.GetString("Check_LimitTraffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifique-me se eu copiar algo.
        /// </summary>
        internal static string Check_NotifyOfCopy {
            get {
                return ResourceManager.GetString("Check_NotifyOfCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo Online.
        /// </summary>
        internal static string Check_OnlineMode {
            get {
                return ResourceManager.GetString("Check_OnlineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir com Windows.
        /// </summary>
        internal static string Check_OpenWithWin {
            get {
                return ResourceManager.GetString("Check_OpenWithWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar em arquivo.
        /// </summary>
        internal static string Check_SaveToFile {
            get {
                return ResourceManager.GetString("Check_SaveToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar botão de doação no formulário principal.
        /// </summary>
        internal static string Check_ShowDonation {
            get {
                return ResourceManager.GetString("Check_ShowDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Começar Minimizado.
        /// </summary>
        internal static string Check_StartMinimized {
            get {
                return ResourceManager.GetString("Check_StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar na inicialização.
        /// </summary>
        internal static string Check_UpdateOnStartup {
            get {
                return ResourceManager.GetString("Check_UpdateOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usar carimbo de data e hora.
        /// </summary>
        internal static string Check_UseTimestamp {
            get {
                return ResourceManager.GetString("Check_UseTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use o ícone branco na barra de tarefas do sistema.
        /// </summary>
        internal static string Check_UseWhiteIcon {
            get {
                return ResourceManager.GetString("Check_UseWhiteIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escreva em tempo real.
        /// </summary>
        internal static string Check_WriteInRealTime {
            get {
                return ResourceManager.GetString("Check_WriteInRealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        internal static string ComboBox_Time_Hour {
            get {
                return ResourceManager.GetString("ComboBox_Time_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo.
        /// </summary>
        internal static string ComboBox_Time_Sec {
            get {
                return ResourceManager.GetString("ComboBox_Time_Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo de texto|*.txt.
        /// </summary>
        internal static string File_TextFile {
            get {
                return ResourceManager.GetString("File_TextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEEDS TRANSLATION.
        /// </summary>
        internal static string Group_GroupSettings {
            get {
                return ResourceManager.GetString("Group_GroupSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        internal static string GroupBox_Actions {
            get {
                return ResourceManager.GetString("GroupBox_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comportamento e recursos visuais.
        /// </summary>
        internal static string GroupBox_BehaviourAndVisuals {
            get {
                return ResourceManager.GetString("GroupBox_BehaviourAndVisuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itens copiados.
        /// </summary>
        internal static string GroupBox_CopiedItems {
            get {
                return ResourceManager.GetString("GroupBox_CopiedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geral.
        /// </summary>
        internal static string GroupBox_General {
            get {
                return ResourceManager.GetString("GroupBox_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comportamento do aplicativo online.
        /// </summary>
        internal static string GroupBox_OnlineBehaviour {
            get {
                return ResourceManager.GetString("GroupBox_OnlineBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações online.
        /// </summary>
        internal static string GroupBox_OnlineSettings {
            get {
                return ResourceManager.GetString("GroupBox_OnlineSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar nas configurações do arquivo.
        /// </summary>
        internal static string GroupBox_SaveToFileSettings {
            get {
                return ResourceManager.GetString("GroupBox_SaveToFileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atraso antes de reconectar.
        /// </summary>
        internal static string GroupBox_TimeBeforeReconnect {
            get {
                return ResourceManager.GetString("GroupBox_TimeBeforeReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar informações da versão.
        /// </summary>
        internal static string GroupBox_UpdateAndCurrentVersion {
            get {
                return ResourceManager.GetString("GroupBox_UpdateAndCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cada.
        /// </summary>
        internal static string Label_Every {
            get {
                return ResourceManager.GetString("Label_Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localização de arquivo.
        /// </summary>
        internal static string Label_FileLocation {
            get {
                return ResourceManager.GetString("Label_FileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEEDS TRANSLATION.
        /// </summary>
        internal static string Label_GroupId {
            get {
                return ResourceManager.GetString("Label_GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Língua.
        /// </summary>
        internal static string Label_Lang {
            get {
                return ResourceManager.GetString("Label_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuto.
        /// </summary>
        internal static string Label_Minutes {
            get {
                return ResourceManager.GetString("Label_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desculpe! Parece que você não tem um administrador
        ///direitos e o aplicativo falhou
        ///para começar como tal, tente
        ///para reiniciar o aplicativo como administrador..
        /// </summary>
        internal static string Label_NoAdminRights {
            get {
                return ResourceManager.GetString("Label_NoAdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defina como o aplicativo lidará
        ///interações online com outros dispositivos..
        /// </summary>
        internal static string Label_OnlineBehaviourExplanation {
            get {
                return ResourceManager.GetString("Label_OnlineBehaviourExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEEDS TRANSLATION.
        /// </summary>
        internal static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundos.
        /// </summary>
        internal static string Label_Seconds {
            get {
                return ResourceManager.GetString("Label_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar notificação por (segundos).
        /// </summary>
        internal static string Label_ShowNotificationFor {
            get {
                return ResourceManager.GetString("Label_ShowNotificationFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versão .
        /// </summary>
        internal static string Label_Version {
            get {
                return ResourceManager.GetString("Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quando fecho a janela principal.
        /// </summary>
        internal static string Label_WhenMainWindowClosed {
            get {
                return ResourceManager.GetString("Label_WhenMainWindowClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se o tempo real estiver desativado, o
        ///aplicação terá apenas acesso e
        ///escreva no arquivo quando estiver fechado..
        /// </summary>
        internal static string Label_WriteRealTimeInfo {
            get {
                return ResourceManager.GetString("Label_WriteRealTimeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard Monitor Lite.
        /// </summary>
        internal static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área de transferência vazia.
        /// </summary>
        internal static string Menu_EmptyClipboard {
            get {
                return ResourceManager.GetString("Menu_EmptyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to História vazia.
        /// </summary>
        internal static string Menu_EmptyHistory {
            get {
                return ResourceManager.GetString("Menu_EmptyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saída.
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        internal static string Menu_Restore {
            get {
                return ResourceManager.GetString("Menu_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vou ocultar o botão imediatamente, mas
        ///antes de fazer isso, eu só queria dizer,
        ///Eu trabalho neste aplicativo principalmente sozinho,
        ///com a ajuda de alguns amigos,
        ///mas não recebo ajuda financeira, não tenho
        ///desejo pedir dinheiro às pessoas apenas
        ///para usar este aplicativo, e eu me recuso a
        ///inclua anúncios de qualquer maneira. Se você gostaria de
        ///apoiar meu trabalho e me ajudar a melhorá-los
        ///o futuro, por favor considere doar, obrigado! :).
        /// </summary>
        internal static string MsgBox_DonateHide {
            get {
                return ResourceManager.GetString("MsgBox_DonateHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para aplicar as alterações, reinicie o aplicativo..
        /// </summary>
        internal static string MsgBox_RestartApp {
            get {
                return ResourceManager.GetString("MsgBox_RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocultar botão de doação.
        /// </summary>
        internal static string MsgBox_Title_DonateHide {
            get {
                return ResourceManager.GetString("MsgBox_Title_DonateHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reiniciar o aplicativo.
        /// </summary>
        internal static string MsgBox_TitleRestartApp {
            get {
                return ResourceManager.GetString("MsgBox_TitleRestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplicativo ainda está sendo executado! Se você deseja sair, clique com o botão direito do mouse no ícone da barra de tarefas e escolha Sair!.
        /// </summary>
        internal static string Notif_AppStillRunning {
            get {
                return ResourceManager.GetString("Notif_AppStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item copiado para a área de transferência!.
        /// </summary>
        internal static string Notif_ItemCopied {
            get {
                return ResourceManager.GetString("Notif_ItemCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicativo ainda em execução!.
        /// </summary>
        internal static string Notif_Title_AppStillRunning {
            get {
                return ResourceManager.GetString("Notif_Title_AppStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item copiado!.
        /// </summary>
        internal static string Notif_Title_ItemCopied {
            get {
                return ResourceManager.GetString("Notif_Title_ItemCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opções.
        /// </summary>
        internal static string Options_Title {
            get {
                return ResourceManager.GetString("Options_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexar Arquivo.
        /// </summary>
        internal static string Radio_Append {
            get {
                return ResourceManager.GetString("Radio_Append", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esvaziar e substituir arquivo.
        /// </summary>
        internal static string Radio_EmptyAndReplace {
            get {
                return ResourceManager.GetString("Radio_EmptyAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair da aplicação.
        /// </summary>
        internal static string Radio_ExitApp {
            get {
                return ResourceManager.GetString("Radio_ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimizar para a bandeja.
        /// </summary>
        internal static string Radio_Minimize {
            get {
                return ResourceManager.GetString("Radio_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receber apenas.
        /// </summary>
        internal static string Radio_ReceiveOnly {
            get {
                return ResourceManager.GetString("Radio_ReceiveOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar e Receber.
        /// </summary>
        internal static string Radio_SendAndReceive {
            get {
                return ResourceManager.GetString("Radio_SendAndReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envie apenas.
        /// </summary>
        internal static string Radio_SendOnly {
            get {
                return ResourceManager.GetString("Radio_SendOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar histórico como arquivo de texto.
        /// </summary>
        internal static string SaveAsTextFile {
            get {
                return ResourceManager.GetString("SaveAsTextFile", resourceCulture);
            }
        }
    }
}
