//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipboardMonitorLite.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipboardMonitorLite.Languages.lang_en", typeof(lang_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Btn_About {
            get {
                return ResourceManager.GetString("Btn_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Btn_Apply {
            get {
                return ResourceManager.GetString("Btn_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Btn_Browse {
            get {
                return ResourceManager.GetString("Btn_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string Btn_CheckForUpdates {
            get {
                return ResourceManager.GetString("Btn_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Btn_Close {
            get {
                return ResourceManager.GetString("Btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Clipboard.
        /// </summary>
        internal static string Btn_EmptyClipboard {
            get {
                return ResourceManager.GetString("Btn_EmptyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty History.
        /// </summary>
        internal static string Btn_EmptyHistory {
            get {
                return ResourceManager.GetString("Btn_EmptyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Btn_MoreOptions {
            get {
                return ResourceManager.GetString("Btn_MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto clear clipboard.
        /// </summary>
        internal static string Check_AutoClearClipboard {
            get {
                return ResourceManager.GetString("Check_AutoClearClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify me if I copy something.
        /// </summary>
        internal static string Check_NotifyOfCopy {
            get {
                return ResourceManager.GetString("Check_NotifyOfCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with Windows.
        /// </summary>
        internal static string Check_OpenWithWin {
            get {
                return ResourceManager.GetString("Check_OpenWithWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to file.
        /// </summary>
        internal static string Check_SaveToFile {
            get {
                return ResourceManager.GetString("Check_SaveToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show donation button on main form.
        /// </summary>
        internal static string Check_ShowDonation {
            get {
                return ResourceManager.GetString("Check_ShowDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start MInimized.
        /// </summary>
        internal static string Check_StartMinimized {
            get {
                return ResourceManager.GetString("Check_StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update on startup.
        /// </summary>
        internal static string Check_UpdateOnStartup {
            get {
                return ResourceManager.GetString("Check_UpdateOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use white icon in system taskbar.
        /// </summary>
        internal static string Check_UseWhiteIcon {
            get {
                return ResourceManager.GetString("Check_UseWhiteIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write in real time.
        /// </summary>
        internal static string Check_WriteInRealTime {
            get {
                return ResourceManager.GetString("Check_WriteInRealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string ComboBox_Time_Hour {
            get {
                return ResourceManager.GetString("ComboBox_Time_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string ComboBox_Time_Min {
            get {
                return ResourceManager.GetString("ComboBox_Time_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        internal static string ComboBox_Time_Sec {
            get {
                return ResourceManager.GetString("ComboBox_Time_Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text file|*.txt.
        /// </summary>
        internal static string File_TextFile {
            get {
                return ResourceManager.GetString("File_TextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string GroupBox_Actions {
            get {
                return ResourceManager.GetString("GroupBox_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviour and Visuals.
        /// </summary>
        internal static string GroupBox_BehaviourAndVisuals {
            get {
                return ResourceManager.GetString("GroupBox_BehaviourAndVisuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied items.
        /// </summary>
        internal static string GroupBox_CopiedItems {
            get {
                return ResourceManager.GetString("GroupBox_CopiedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string GroupBox_General {
            get {
                return ResourceManager.GetString("GroupBox_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to file settings.
        /// </summary>
        internal static string GroupBox_SaveToFileSettings {
            get {
                return ResourceManager.GetString("GroupBox_SaveToFileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update and current version info.
        /// </summary>
        internal static string GroupBox_UpdateAndCurrentVersion {
            get {
                return ResourceManager.GetString("GroupBox_UpdateAndCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every.
        /// </summary>
        internal static string Label_Every {
            get {
                return ResourceManager.GetString("Label_Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Location.
        /// </summary>
        internal static string Label_FileLocation {
            get {
                return ResourceManager.GetString("Label_FileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Label_Lang {
            get {
                return ResourceManager.GetString("Label_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! Seems like you have no admin
        ///rights, or the application failed
        ///to start up as such, please try
        ///to restart the application as administrator..
        /// </summary>
        internal static string Label_NoAdminRights {
            get {
                return ResourceManager.GetString("Label_NoAdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notification for (Seconds).
        /// </summary>
        internal static string Label_ShowNotificationFor {
            get {
                return ResourceManager.GetString("Label_ShowNotificationFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version .
        /// </summary>
        internal static string Label_Version {
            get {
                return ResourceManager.GetString("Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When I close the main window.
        /// </summary>
        internal static string Label_WhenMainWindowClosed {
            get {
                return ResourceManager.GetString("Label_WhenMainWindowClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If real time is turned off, the
        ///application will only access and
        ///write to the file when it&apos;s closed..
        /// </summary>
        internal static string Label_WriteRealTimeInfo {
            get {
                return ResourceManager.GetString("Label_WriteRealTimeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard Monitor Lite.
        /// </summary>
        internal static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Clipboard.
        /// </summary>
        internal static string Menu_EmptyClipboard {
            get {
                return ResourceManager.GetString("Menu_EmptyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty History.
        /// </summary>
        internal static string Menu_EmptyHistory {
            get {
                return ResourceManager.GetString("Menu_EmptyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Menu_Restore {
            get {
                return ResourceManager.GetString("Menu_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ll hide the button right away, but before doing so, I just wanted to say, I work on this application mostly alone, with some help from a few friends, but I get no financial aid, I have no desire to ask for money from people just to use this application, and I refuse to include ads in any form. If you&apos;d like to support my work and help me improve them in the future, please consider donating, thank you! :).
        /// </summary>
        internal static string MsgBox_DonateHide {
            get {
                return ResourceManager.GetString("MsgBox_DonateHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To apply changes, please restart the application..
        /// </summary>
        internal static string MsgBox_RestartApp {
            get {
                return ResourceManager.GetString("MsgBox_RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide donation button.
        /// </summary>
        internal static string MsgBox_Title_DonateHide {
            get {
                return ResourceManager.GetString("MsgBox_Title_DonateHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart app.
        /// </summary>
        internal static string MsgBox_TitleRestartApp {
            get {
                return ResourceManager.GetString("MsgBox_TitleRestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is still running! If you&apos;d like to exit, please right click on the taskbar icon and choose Exit!.
        /// </summary>
        internal static string Notif_AppStillRunning {
            get {
                return ResourceManager.GetString("Notif_AppStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item copied to clipboard!.
        /// </summary>
        internal static string Notif_ItemCopied {
            get {
                return ResourceManager.GetString("Notif_ItemCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application still running!.
        /// </summary>
        internal static string Notif_Title_AppStillRunning {
            get {
                return ResourceManager.GetString("Notif_Title_AppStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item copied!.
        /// </summary>
        internal static string Notif_Title_ItemCopied {
            get {
                return ResourceManager.GetString("Notif_Title_ItemCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options_Title {
            get {
                return ResourceManager.GetString("Options_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append file.
        /// </summary>
        internal static string Radio_Append {
            get {
                return ResourceManager.GetString("Radio_Append", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty file and replace.
        /// </summary>
        internal static string Radio_EmptyAndReplace {
            get {
                return ResourceManager.GetString("Radio_EmptyAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the application.
        /// </summary>
        internal static string Radio_ExitApp {
            get {
                return ResourceManager.GetString("Radio_ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize on system tray.
        /// </summary>
        internal static string Radio_Minimize {
            get {
                return ResourceManager.GetString("Radio_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save history as text file.
        /// </summary>
        internal static string SaveAsTextFile {
            get {
                return ResourceManager.GetString("SaveAsTextFile", resourceCulture);
            }
        }
    }
}
