//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipboardMonitorLite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_hu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_hu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipboardMonitorLite.lang_hu", typeof(lang_hu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Információ.
        /// </summary>
        internal static string Btn_About {
            get {
                return ResourceManager.GetString("Btn_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alkalmazás.
        /// </summary>
        internal static string Btn_Apply {
            get {
                return ResourceManager.GetString("Btn_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Btn_Browse {
            get {
                return ResourceManager.GetString("Btn_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frissítések keresése.
        /// </summary>
        internal static string Btn_CheckForUpdates {
            get {
                return ResourceManager.GetString("Btn_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezárás.
        /// </summary>
        internal static string Btn_Close {
            get {
                return ResourceManager.GetString("Btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vágólap kiürítése.
        /// </summary>
        internal static string Button_EmptyClipboard {
            get {
                return ResourceManager.GetString("Button_EmptyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Előzmények törlése.
        /// </summary>
        internal static string Button_EmptyHistory {
            get {
                return ResourceManager.GetString("Button_EmptyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beállítások.
        /// </summary>
        internal static string Button_MoreOptions {
            get {
                return ResourceManager.GetString("Button_MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vágólap autómatikus kiürítése.
        /// </summary>
        internal static string Check_AutoClearClipboard {
            get {
                return ResourceManager.GetString("Check_AutoClearClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Értesíts, amikor kimásolok valamit.
        /// </summary>
        internal static string Check_NotifyOfCopy {
            get {
                return ResourceManager.GetString("Check_NotifyOfCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indulás Windows-al.
        /// </summary>
        internal static string Check_OpenWithWin {
            get {
                return ResourceManager.GetString("Check_OpenWithWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimásolt szövegek File-ba mentése.
        /// </summary>
        internal static string Check_SaveToFile {
            get {
                return ResourceManager.GetString("Check_SaveToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adomány gomb megjelenítése.
        /// </summary>
        internal static string Check_ShowDonation {
            get {
                return ResourceManager.GetString("Check_ShowDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indulás kicsiben.
        /// </summary>
        internal static string Check_StartMinimized {
            get {
                return ResourceManager.GetString("Check_StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frissítés amikor az alkalmazás elindul.
        /// </summary>
        internal static string Check_UpdateOnStartup {
            get {
                return ResourceManager.GetString("Check_UpdateOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Világos ikon használata a tálcán.
        /// </summary>
        internal static string Check_UseWhiteIcon {
            get {
                return ResourceManager.GetString("Check_UseWhiteIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valós-időben való file írás.
        /// </summary>
        internal static string Check_WriteInRealTime {
            get {
                return ResourceManager.GetString("Check_WriteInRealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Óra.
        /// </summary>
        internal static string ComboBox_Time_Hour {
            get {
                return ResourceManager.GetString("ComboBox_Time_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perc.
        /// </summary>
        internal static string ComboBox_Time_Min {
            get {
                return ResourceManager.GetString("ComboBox_Time_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Másodperc.
        /// </summary>
        internal static string ComboBox_Time_Sec {
            get {
                return ResourceManager.GetString("ComboBox_Time_Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szöveges file|*.txt.
        /// </summary>
        internal static string File_TextFile {
            get {
                return ResourceManager.GetString("File_TextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Műveletek.
        /// </summary>
        internal static string GroupBox_Actions {
            get {
                return ResourceManager.GetString("GroupBox_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viselkedés és kinézet.
        /// </summary>
        internal static string GroupBox_BehaviourAndVisuals {
            get {
                return ResourceManager.GetString("GroupBox_BehaviourAndVisuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimásolt elemek.
        /// </summary>
        internal static string GroupBox_CopiedItems {
            get {
                return ResourceManager.GetString("GroupBox_CopiedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Általános.
        /// </summary>
        internal static string GroupBox_General {
            get {
                return ResourceManager.GetString("GroupBox_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File-ba mentés beállításai.
        /// </summary>
        internal static string GroupBox_SaveToFileSettings {
            get {
                return ResourceManager.GetString("GroupBox_SaveToFileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frissítés és jelenlegi verzió.
        /// </summary>
        internal static string GroupBox_UpdateAndCurrentVersion {
            get {
                return ResourceManager.GetString("GroupBox_UpdateAndCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minden.
        /// </summary>
        internal static string Label_Every {
            get {
                return ResourceManager.GetString("Label_Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File helye.
        /// </summary>
        internal static string Label_FileLocation {
            get {
                return ResourceManager.GetString("Label_FileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyelv.
        /// </summary>
        internal static string Label_Lang {
            get {
                return ResourceManager.GetString("Label_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úgy tűnik hogy nincs Admin jogod, illetve
        ///az alkalmazás nem tudott újraindulni
        ///admin jogokkal, kérlek próbáld meg
        ///újraindítani az alkalmazást, mint
        ///Adminisztrátor!.
        /// </summary>
        internal static string Label_NoAdminRights {
            get {
                return ResourceManager.GetString("Label_NoAdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Értesítés megjelenítése (másodperc):.
        /// </summary>
        internal static string Label_ShowNotificationFor {
            get {
                return ResourceManager.GetString("Label_ShowNotificationFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzió .
        /// </summary>
        internal static string Label_Version {
            get {
                return ResourceManager.GetString("Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amikor a fő ablakot bezárom.
        /// </summary>
        internal static string Label_WhenMainWindowClosed {
            get {
                return ResourceManager.GetString("Label_WhenMainWindowClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amennyiben nem valós időben van file
        ///hozzáférés, az alkalmazás kilépéskor
        ///fog a file-ba írni..
        /// </summary>
        internal static string Label_WriteRealTimeInfo {
            get {
                return ResourceManager.GetString("Label_WriteRealTimeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vágólap-Monitor (Lite).
        /// </summary>
        internal static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vágólap kiürítése.
        /// </summary>
        internal static string Menu_EmptyClipboard {
            get {
                return ResourceManager.GetString("Menu_EmptyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Előzmények törlése.
        /// </summary>
        internal static string Menu_EmptyHistory {
            get {
                return ResourceManager.GetString("Menu_EmptyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilépés.
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megnyit.
        /// </summary>
        internal static string Menu_Restore {
            get {
                return ResourceManager.GetString("Menu_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azonnal el fogom rejteni! Viszont előtte szerettem volna valamit mondani. Ezt az alkalmazást leginkább egyedül fejlesztem, és nincs anyagi segítség, az alkalmazásért nem kérek pénzt, és nem vagyok hajlandó hírdetéseket tenni bele. Amennyiben van rá lehetőséged és tetszik az alkalmazás, kérlek gondold meg hogy adományozol, köszönöm! :).
        /// </summary>
        internal static string MsgBox_DonateHide {
            get {
                return ResourceManager.GetString("MsgBox_DonateHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A változásokhoz kérlek indítsd újra az alkalmazást!.
        /// </summary>
        internal static string MsgBox_RestartApp {
            get {
                return ResourceManager.GetString("MsgBox_RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adomány gomb elrejtése.
        /// </summary>
        internal static string MsgBox_Title_DonateHide {
            get {
                return ResourceManager.GetString("MsgBox_Title_DonateHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Újraindítás.
        /// </summary>
        internal static string MsgBox_TitleRestartApp {
            get {
                return ResourceManager.GetString("MsgBox_TitleRestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az applikáció még fut! Amennyiben teljesen ki szeretne lépni, kattintson jobb gombbal az asztali ikonra és kattintson a Kilépésre..
        /// </summary>
        internal static string Notif_AppStillRunning {
            get {
                return ResourceManager.GetString("Notif_AppStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szöveg kimásolva!.
        /// </summary>
        internal static string Notif_ItemCopied {
            get {
                return ResourceManager.GetString("Notif_ItemCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az applikáció a háttérben fut!.
        /// </summary>
        internal static string Notif_Title_AppStillRunning {
            get {
                return ResourceManager.GetString("Notif_Title_AppStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Másolás megtörtént!.
        /// </summary>
        internal static string Notif_Title_ItemCopied {
            get {
                return ResourceManager.GetString("Notif_Title_ItemCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beállítások.
        /// </summary>
        internal static string Options_Title {
            get {
                return ResourceManager.GetString("Options_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiegészítés.
        /// </summary>
        internal static string Radio_Append {
            get {
                return ResourceManager.GetString("Radio_Append", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File kiürítése és újraírása.
        /// </summary>
        internal static string Radio_EmptyAndReplace {
            get {
                return ResourceManager.GetString("Radio_EmptyAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilépés.
        /// </summary>
        internal static string Radio_ExitApp {
            get {
                return ResourceManager.GetString("Radio_ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tálcára kicsibe.
        /// </summary>
        internal static string Radio_Minimize {
            get {
                return ResourceManager.GetString("Radio_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Előzmények elmentése szöveges file-ba.
        /// </summary>
        internal static string SaveAsTextFile {
            get {
                return ResourceManager.GetString("SaveAsTextFile", resourceCulture);
            }
        }
    }
}
